@startuml
' Usecase: human labeling a set of data and uploading to splash-ml
' precondition 1: images are known to splash-ml with prexisting labels
' precondition 2: project has already been created containing allowed labels and list of images
' Alex has gathered undergrads, asks them to label pool of images, collects this in project
actor human as H
participant labelmaker as A
participant splash_ml as TS
participant data_service as DS

H ->> A: REQUEST Show image in project
' how does user know what data pool to pull from?
activate A
    A ->> TS: QUERY random image in project
    TS -->> A: RETURN image URL + tag categories?
    A ->> DS: GET Image (from URL)
    DS -->> A: RETURN Image
    A ->> H: SHOW Image + existing tag categories?
deactivate A
H ->> A: ADD Tags to image
activate A
    A ->> TS: ADD Tags to image
deactivate A
@enduml