@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

left to right direction

entity tagger{
    * **uid**
    __
    type
    name
}

entity tagging_event{
    * **uid**
    __
    * taggerl_id
    run_time
    accuracy
}

entity asset{
    * **uid**
    ___
    * event_id
    * asset_id
    asset_locator
    tags

}

entity tags <<sub-document>> {
    * tag 
    * confidence
    * event_id
}


tagger ||..o{ tagging_event
tagging_event ||..o{ asset
asset ||..o{ tags
@enduml
